### ISSUE TITLE
Convex helper cache failed to compile =

### ISSUE THREAD

**Issue by larryhopecode** [get-convex/convex-helpers#147]
The error message: 
./node_modules/.pnpm/convex-helpers@0.1.43_convex@1.12.2_react-dom@18.3.1_react@18.3.1__react@18.3.1__react@18.3.1_zod@3.23.8/node_modules/convex-helpers/react/cache/provider.tsx:115:3
Type error: Private identifiers are only available when targeting ECMAScript 2015 and higher.

Then even I change tsconfig.json:
"target": "ES2020". 
The result is the same.

**Comment by LarHope** [comment]
Compiling error could be fixed by change private function #getQueryEntry to   _getQueryEntry
And wait for better solution.

**Comment by marwand** [comment]
I'm getting a different error with the same file (provider.tsx):
Unable to resolve "./provider.js" from "node_modules/convex-helpers/react/cache/hooks.ts"

**Comment by ianmacartney** [comment]
@larryhopecode sorry for the delay here - was on vacation for a couple weeks. 
I'm surprised changing the tsconfig didn't fix it for you - did you change it in the tsconfig in your project root and in the convex/ folder? I target ESNext with no issues.

**Comment by ianmacartney** [comment]
I'm going to dig into the helper more soon and will change it away from the private identifier, thanks for flagging that and sorry you hit it

**Comment by ianmacartney** [comment]
@marwand I believe your issue is around module resolution or jsx. 
I'm not an expert in tsconfigs unfortunately but I'd try using `module` as `ESNext` and `moduleResolution` as `Node` or `bundler` and `jsx` as `react-jsx`

**Comment by LarHope** [comment]
Change to ESNext or other value is still the same result. But change it away from the private identifier works nicely.
I use pnpm patch and working fine. Here are the lines changed:

-  #getQueryEntry(
+  _getQueryEntry

-    const entry = this.#getQueryEntry(queryKey);
+    const entry = this._getQueryEntry(queryKey);

-    let entry = this.#getQueryEntry(queryKey);
+    let entry = this._getQueryEntry(queryKey);

-        for (const ref of e.refs.values()) {
+        for (const ref of Array.from(e.refs.values())) {

-    for (const [k, v] of this.subs.entries()) {
+    Array.from(this.subs.entries()).forEach(([k, v]) => {

-    for (const [k, v] of this.queries.entries()) {
+    Array.from(this.queries.entries()).forEach(([k, v]) => {

**Comment by ianmacartney** [comment]
Resolved in 0.1.48
