### ISSUE TITLE
Query Caching on Expo / React native

### ISSUE THREAD

**Issue by marwand** [get-convex/convex-helpers#211]
Hi! 
      
Firstly, thank you for your work on this project! 🙂

I'm here to report a bug that prevents using Query Caching on expo/react-native. This is an extension of the discussion on this thread: https://discord.com/channels/1019350475847499849/1272012043582574664

**The Problem**

After setting up ConvexQueryCacheProvider from "convex-helpers/react/cache/provider"
and using useQuery from "convex-helpers/react/cache/hooks", I get the following error:
``` Could not find `ConvexQueryCacheContext`! This `useQuery` implementation must be used in the React component tree under `ConvexQueryCacheProvider`. Did you forget it? ```

**A workaround**

Upon investigating the code, I found that I'm importing ConvexQueryCacheProvider from ```convex-helpers/react/cache/provider```, while ```convex-helpers/react/cache/hooks.ts``` imports it from ```convex-helpers/react/cache/provider.js```.

I guess there are two instances of the context, one in the .tsx file and on in the .js file.

To get around this, in my application, I imported the cache provider from the javascript version.
```import { ConvexQueryCacheProvider } from "convex-helpers/react/cache/provider.js"```

Now this caused another issue, of crypto being undefined. 
```TypeError: crypto.randomUUID is not a function (it is undefined)``` 

I'm guessing with next.js, crypto is readily available, as opposed to with expo/react-native. I got around this by replacing the crypto reference with UUID. (And of course, adding uuid as a dependency (not shown in patch))

Here is the diff that fixes the crypto issue:

```diff --git a/node_modules/convex-helpers/react/cache/hooks.ts b/node_modules/convex-helpers/react/cache/hooks.ts
index ac83e9c..967cb9e 100644
--- a/node_modules/convex-helpers/react/cache/hooks.ts
+++ b/node_modules/convex-helpers/react/cache/hooks.ts
@@ -12,7 +12,7 @@ import {
 import { useContext, useEffect, useState } from "react";
 import { ConvexQueryCacheContext } from "./provider.js";
 import { convexToJson } from "convex/values";
-
+import { v4 as uuidv4 } from 'uuid';
 /**
  * Load a variable number of reactive Convex queries, utilizing
  * the query cache.
@@ -90,7 +90,7 @@ export function useQueries(
     () => {
       const ids: string[] = [];
       for (const [key, { query, args }] of Object.entries(queries)) {
-        const id = crypto.randomUUID();
+        const id = uuidv4();
         registry.start(id, queryKeys[key]!, query, args, (v) =>
           setValues((old) => {
             if (!(key in old)) return old; // We're no longer tracking this query
```

**Comment by ianmacartney** [comment]
Thanks for the report and investigation @marwand !
I just cut an alpha release that I hope fixes the issue for you: Can you verify  `npm i convex-helpers@0.1.51-alpha.4` works for you? If it's looking good I'll release an official version tomorrow.

I changed it so you can import both the provider and hooks from the same file:
```ts
import { ConvexQueryCacheProvider } from "convex-helpers/react/cache";
```
and
```ts
import { useQuery } from "convex-helpers/react/cache";
```

Hopefully this fixes the resolution issue.

For the crypto issue - I just dropped in an ID generator that doesn't rely on crypto (if crypto doesn't exist) - it has >100 bits of randomness, which is more than enough.

Please re-open if you still see issues 🙏
