### ISSUE TITLE
Convex helper types error, when building next.js application

### ISSUE THREAD

**Issue by jainmanshu** [get-convex/convex-helpers#213]
Hey,

I am using `convex-helper` library specifically using `SessionProvider` to generate client based session via local storage option. After installing the library and adding logic for session handling, it seems to be running fine when I run my next-js application locally. 

But when I am try to deploy my next build, I am getting a lint error throw by `./node-modules/convex-helpers/index.ts`  file and the error is 

`Type error: Type 'Iterable<FromType>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.` at line 15, see attached image

![image](https://github.com/user-attachments/assets/94e666f9-2619-4ee5-89cd-c66e1e52cb84)

I used the hint provided in the error  to help fix it, however I can't seem to figure out what's wrong after following the hint, my `tsconfig` file is default provided `next-js` template.

**Comment by ianmacartney** [comment]
A few questions, and apologies I'll be out of the office for 12 days
starting tomorrow.

Are you deploying on Vercel or elsewhere?
Does npm run build work locally?
What does your convex & next tsconfig look like?

**Comment by jainmanshu** [comment]
Are you deploying on Vercel or elsewhere? - Yeah I am deploying on Vercel
Does npm run build work locally? - it doesn't build locally as well same error
What does your convex & next tsconfig look like? - I haven't made any change but here are config

`convex/tsconfig`

```
{
  /* This TypeScript project config describes the environment that
   * Convex functions run in and is used to typecheck them.
   * You can modify it, but some settings required to use Convex.
   */
  "compilerOptions": {
    /* These settings are not required by Convex and can be modified. */
    "allowJs": true,
    "strict": true,
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,

    /* These compiler options are required by Convex */
    "target": "ESNext",
    "lib": ["ES2021", "dom"],
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["./**/*"],
  "exclude": ["./_generated"]
}

```

`next-js/tsconfig`

```
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}

```

**Comment by ianmacartney** [comment]
It looks like you don't have a "target" set in your root tsconfig - try
setting it to "ESNext"

**Comment by jainmanshu** [comment]
Yeah it worked! I will close the issue.

Thanks for the help!
