### ISSUE TITLE
Compile error when attempting to build on Vercel after introducing migrations

### ISSUE THREAD

**Issue by uzair223** [get-convex/convex-helpers#305]
Hi all,

I am getting this error after introducing migrations to my convex app.

I am using nextjs 14.2.14 and convex-helpers 0.1.60

```
Failed to compile.
./node_modules/convex-helpers/index.ts:15:22
Type error: Type 'Iterable<FromType>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
  13 |   const promises: Promise<ToType>[] = [];
  14 |   let index = 0;
> 15 |   for (const item of await list) {
     |                      ^
  16 |     promises.push(asyncTransform(item, index));
  17 |     index += 1;
  18 |   }
✖ 'npm run build' failed
Error: Command "npx convex deploy --cmd 'npm run build' && npx convex run migrations --prod" exited with 1
```

This is `migrations.ts` that I added:
```
import {
  makeMigration,
  startMigration,
  startMigrationsSerially,
} from "convex-helpers/server/migrations";
import { internalMutation } from "./_generated/server";
import { internal } from "./_generated/api";

const migration = makeMigration(internalMutation, {
  migrationTable: "migrations",
});

export const myMigration = migration({
  table: "myTable",
  async migrateOne(ctx, doc) {
   // ...
});

export default internalMutation(async (ctx) => {
  await startMigrationsSerially(ctx, [
    internal.migrations.myMigration,
    // ...
  ]);
});
```

**Comment by tanmay-pathak** [comment]
@uzair223 - I am running into the same error. Were you able to fix this?

**Comment by uzair223** [comment]
@tanmay-pathak - I was able to fix the error. Unfortunately, I don't completely recall how I did though haha;
I believe I enabled the `downlevelIteration` flag on both my root `tsconfig.json` and `convex/tsconfig.json`.

**Comment by ianmacartney** [comment]
In tsconfig compilerOptions, what value do you have for `target`? Any reason to not bump up that target in `convex/tsconfig.json` to something like `ESNext`?

**Comment by ianmacartney** [comment]
I cut `convex-helpers@0.1.65-alpha.0` if anyone wants to give that a shot - I couldn't reproduce but it should be safe & easier on the older targets

**Comment by tanmay-pathak** [comment]
I added `ESNext` as the target after reading another issue #213. My builds on Vercel are successful but running `npm run build` locally still fails with the same `Type error: Type 'Iterable<FromType>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.`.  

<details>
<summary>I have added my full tsconfig.json here.</summary>

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

</details>

**Comment by tanmay-pathak** [comment]
@ianmacartney - Using `"convex-helpers": "0.1.65-alpha.0",` in my `package.json` works! `npm run build` no longer fails locally.

**Comment by ianmacartney** [comment]
amazing! I'll cut a release with that in `0.1.65` soon

**Comment by ianmacartney** [comment]
released
