### ISSUE TITLE
zodToConvexFields interprets ZodDefault as optional

### ISSUE THREAD

**Issue by ericdew** [get-convex/convex-helpers#69]
When creating table fields using zod, adding a default return to the zod schema results in the field schema being optional.

`z.string()` will be interpreted as `v.string()`
`z.string().default("defaultValue")` will be interpreted as `v.optional(v.string())`

Example implementation/use case:

```js
import { defineEnt, defineEntSchema, getEntDefinitions } from "convex-ents";
import { zodToConvexFields } from "convex-helpers/server/zod";
import { z } from "zod";

const user = {
  userId: z.string().default(someDefaultIdGenerator()),
  // ^ userId: v.optional(v.string())
  // expected: v.string()
};

const schema = defineEntSchema({
  users: defineEnt(zodToConvexFields(user)),
});

const definitions = getEntDefinitions(schema);

type UserId = typeof definitions.users.document.userId;
// ^ string | undefined
// expected: string
```

**Comment by ianmacartney** [comment]
@ericdew This is related to your comment on Transforms #70 - the current version is primarily for argument validation, so it will generate the _input_ types for the zod validator.

For defaults in general, note that these won't be run automatically when database inserts happen. I haven't made a database writer wrapper that can expose such behavior but the gist would be that it wraps inserts to run the zod validator, generating the default value. So I would rely on regular convex validators for table definitions except where it's convenient to share the input validator types.

There's a second thing worth noting here: users will automatically get an _id field when generated. So you don't need to add a `userId` field explicitly.

For a table you probably want to make that required. As a tactical fix, I would suggest:
```
const inputFields = {
  myDefaultField: z.string().default(""),
   ...
};
const myTableFields = {
   ...zodToConvexFields(inputFields),
   myDefaultField: v.string(),
};

defineTable(myTableFields)
// or
defineEntSchema(myTableFields)
```
make sense?

**Comment by ianmacartney** [comment]
If you can get the types working in the `zod` branch, let me know!

**Comment by ianmacartney** [comment]
closing, as it's working as expected (for input validators). can capture the output type request in the other issue
